#ifndef REMOTEDESKTOP_GLOBAL_H
#define REMOTEDESKTOP_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(REMOTEDESKTOP_LIBRARY)
#  define REMOTEDESKTOP_EXPORT Q_DECL_EXPORT
#else
#  define REMOTEDESKTOP_EXPORT Q_DECL_IMPORT
#endif

#endif // REMOTEDESKTOP_GLOBAL_H
